Add CI scripts to build conda packages and run tests
rapidsai/ucxx pull request #18
Opened 2023-04-03 20:50 UTC by pentschev

2023-04-10 15:24 UTC, ajschmidt8 approved these changes

2023-04-10 19:46 UTC, jakirkham reviewed
Thanks Peter! 🙏

Had one question about RAPIDS release version bumps are handled (with respect to `rmm` version used)

2023-04-10 19:46 UTC, jakirkham commented on conda/recipes/ucxx/conda_build_config.yaml
> +  - "23.04.*"
Does this get updated by the `ci/release/update-version.sh` script? If not, should it be?

2023-04-10 19:54 UTC, bdice requested changes
Comments attached.

2023-04-10 19:54 UTC, bdice commented on dependencies.yaml
> +            packages:
Where is `cuda-sanitizer-api` being used? I searched briefly but didn't see it. If it's not used, the entire `specific` section can be deleted.
```suggestion
```

2023-04-10 19:54 UTC, bdice commented on dependencies.yaml
> +      - run
```suggestion
      - run_python
```

2023-04-10 19:54 UTC, bdice commented on dependencies.yaml
> +  run:
```suggestion
  run_python:
```

2023-04-10 19:54 UTC, bdice commented on dependencies.yaml
> +          - numpy>=1.21
Should we use an anchor here and re-use this pinning version in the other places numpy is referenced? See `&gtest` / `*gtest` for an example.

2023-04-10 19:54 UTC, bdice commented on dependencies.yaml
> +      - output_types: [conda, requirements]
Some additional work is probably needed to make this file compatible with generating the build/run/test requirements in `pyproject.toml`. Happy to defer that to a later PR if we can file an issue.
```suggestion
      - output_types: [conda, requirements, pyproject]
```

2023-04-10 19:54 UTC, bdice commented on ci/release/update-version.sh
This file also needs to update `rmm_version` in `conda/recipes/ucxx/conda_build_config.yaml`.

2023-04-10 19:54 UTC, bdice commented on ci/check_style.sh
> +pre-commit run --hook-stage manual --all-files --show-diff-on-failure
```suggestion
pre-commit run --all-files --show-diff-on-failure
```

2023-04-10 19:54 UTC, bdice commented on .pre-commit-config.yaml
I'd recommend updating the hook versions in this file with `pre-commit autoupdate`. Since it's a new package, that should be a better place to start. I am going to be updating hook versions in other RAPIDS repos in the next month or so.

2023-04-10 19:54 UTC, bdice commented on .github/workflows/test.yaml
> +    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-cpp.yaml@branch-23.04
This seems wrong.
```suggestion
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-cpp-tests.yaml@branch-23.04
```

2023-04-11 11:18 UTC, pentschev reviewed
Thanks @jakirkham and @bdice , I've addressed the suggestions

2023-04-11 13:03 UTC, merged