Fix destruction of `ucxx::RequestTagMulti` and final status
rapidsai/ucxx pull request #72
Opened 2023-07-28 14:54 UTC by pentschev

Fix destruction of `ucxx::RequestTagMulti`, which after moving to inheriting from `ucxx::Request`, using `setStatus()` was missing, thus causing the `ucxx::RequestTagMulti` to never cleanup its inflight request status. Calling `setStatus()` instead of writing the `_status` attribute directly resolves this.

The status of `ucxx::RequestTagMulti` was until now always `UCS_INPROGRESS` or `UCS_OK` after completing. This is not right but there is no good way to combine the statuses of all underlying requests. Therefore we now set the status of the first failing request as the final status instead of `UCS_OK` if at least one of the requests failed. The user can still check each underlying's request status if granular information is required.

Since `ucxx::RequestTagMulti` now inherits from `ucxx::Request`, the latter's trace logging for creation/destruction are sufficient, thus removing the redundant trace logs is appropriate.

Also add lifetime trace logs for `ucxx::BufferRequest`.

2023-07-31 17:24 UTC, wence- approved these changes
This looks right to me, thanks.

2023-08-01 11:07 UTC, wence- requested changes
Requesting changes, since I am not sure about two things:

1. Do we need a lock on the whole `Request` object for concurrent modification, or is it sufficient just to lock `_status`?
2. It looks like there are some `Request` calls that modify/read `_status` without a lock. Is this intentional?

2023-08-02 12:08 UTC, pentschev commented
Thanks @wence- for another great review. You raised various valid concerns, I think I have addressed them all via https://github.com/rapidsai/ucxx/pull/72/commits/27d6fbdaf4ee07a0b2f871836b4936d78cb45c16, which now always protects `_status` and `_request` via a `std::recursive_mutex` (to ensure methods like `process()` can still call `setStatus()` without trying to lock twice a non-reentrant mutex twice in the same thread). Would you mind taking another look in case I missed something?

2023-08-02 15:55 UTC, pentschev commented on cpp/src/request.cpp
> +  if (_callback) _callback(status, _callbackData);
Now that the lock is reentrant we can actually hold the lock here, I changed it https://github.com/rapidsai/ucxx/pull/72/commits/c13e98a3cde483e26e1ab0bd97a0a3121458b95f.

2023-08-02 15:55 UTC, pentschev commented on cpp/src/request.cpp
> +               ucs_status_string(_status),
Good catch, that should now be resolved by https://github.com/rapidsai/ucxx/pull/72/commits/c13e98a3cde483e26e1ab0bd97a0a3121458b95f also.

2023-08-02 15:59 UTC, wence- approved these changes
Thanks Peter.

2023-08-02 22:03 UTC, pentschev commented
@wence- I'm merging this in now, but it seems that the main issue with `test_send_recv_multi.py` was the [`rerun_on_failure` fixture](https://github.com/rapidsai/ucxx/blob/branch-0.33/python/ucxx/_lib_async/tests/conftest.py#L71) I added previously, it runs the underlying test but not the [`event_loop` fixture](https://github.com/rapidsai/ucxx/blob/0e3c8aa81765d856e18ba823b7162ba680c380a5/python/ucxx/_lib_async/tests/conftest.py#L40-L52), which is what was failing. Part of the docs mention that [pytest-rerunfailures closes the event loop before the `asyncio_timeout` fixture can run](https://github.com/rapidsai/ucxx/blob/0e3c8aa81765d856e18ba823b7162ba680c380a5/python/ucxx/_lib_async/tests/conftest.py#L64-L67), but right now I couldn't reproduce this. I'm not sure if I've done something differently in the past or if something changes in pytest-rerunfailures. In any case, I think https://github.com/rapidsai/ucxx/pull/72/commits/b0c20b9e5f2529b2aa1771392bbdee4c8baee45d improves things a bit, I'll keep an eye on whether this change will raise any future issues, if not I'll drop `rerun_on_failure` later.

2023-08-02 22:03 UTC, pentschev commented
/merge

2023-08-02 22:03 UTC, merged